### ISSUE TITLE
ubermagutil 1.0 todo-list and discussion

### ISSUE THREAD

**Issue by marijanbeg** [ubermag/ubermagutil#4]
The purpose of this issue is to collect and discuss todo-items on what could/should be done for `ubermagutil` 1.0 future release.

- [ ] Base class for `ubermagtable.Table` and `discretisedfield.Line` to avoid code repetition.
- [x] Code for generating common repository data for all Ubermag repositories
- [ ] Descriptor for callables.
- [ ] Consider moving constants to this package (from `micromagneticmodel`).
